### ISSUE TITLE
Libmr Patented

### ISSUE THREAD

**Issue by bhack** [abhijitbendale/OSDN#1]
I've found a versione of libmr in https://github.com/Vastlab/libMR released under BSD license.
But [here](http://www.metarecognition.com/libmr-license/) I see that there is a patent pending on some libmr methods. Are this related also to fitmax?

**Comment by tboult** [comment]
Thanks for the questions.  We dropped patent associated with libMR and move the IP back to the University of Colorado Colorado Springs.  We then moved to BSD type of license for all of the code in libMR.   I've updated putting a note on metarecognition.com site (where we posted the orginal).   So you are free to use this according to the BSD license herein and use the libMR in Github in the same way.

**Comment by bhack** [comment]
Thank you. /cc @lenlen
