### ISSUE TITLE
Confusion regarding compute distance equation in "openmax_utils.py" file

### ISSUE THREAD

**Issue by otkupjnoz** [abhijitbendale/OSDN#4]
so while computing euclidean distance you have a division by **200** in the equation. 
I couldn't understand why is it required.

query_distance = spd.euclidean(mean_vec[channel, :], query_channel) / **200**.

**Comment by elbaro** [comment]
I think it's because the cosine distance is in [0,1]. When eucos (euclidian + cos) is used, it is natural to match the scales of two.
